spring:
  application:
    name: secure-oauth2-third-party-integration
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - https://www.googleapis.com/auth/drive.readonly
              - profile
              - email
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/google
          github:
            scope:
                - read:user
                - user:email
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access-token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:classpath:application-secret.yaml"
server:
  port: 8081
  servlet:
    context-path: /


